# Generated by Django 3.2.9 on 2021-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrudApp', '0002_alter_student2_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
