# Generated by Django 3.2.9 on 2021-12-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrudApp', '0003_alter_student2_roll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student2',
            new_name='student',
        ),
    ]
