# Generated by Django 3.2.9 on 2021-12-16 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrudApp', '0004_rename_student2_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
